version: '3.1'
services:
  stats-server:
    build: stats/stats-server
    image: stats-server-image
    container_name: stats-server-container
    ports:
      - "9090:9090"

    depends_on:
      - stats-db
    environment:
      - SERVER_PORT=9090
      - MAIN_SERVICE_URL=http://ewm-service:8080
      - SPRING_DATASOURCE_URL=jdbc:postgresql://stats-db:5432/stats
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=iamroot
      - SPRING_DATASOURCE_DRIVER_CLASS_NAME=org.postgresql.Driver

  stats-db:
    image: postgres:14-alpine
    container_name: stats-container-db
    ports:
      - "6541:5432"
    environment:
      - POSTGRES_DB=stats
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=iamroot


  ewm-service:
    build: main-service
    image: ewm-server-image
    container_name: ewm-server-container
    ports:
      - "8080:8080"
    depends_on:
      - ewm-db
    environment:
      - SERVER_PORT=8080
      - STATS_SERVICE_URL=http://stats-server:9090
      - SPRING_DATASOURCE_URL=jdbc:postgresql://ewm-db:5432/ewm
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=iamroot
      - SPRING_DATASOURCE_DRIVER_CLASS_NAME=org.postgresql.Driver


  ewm-db:
    image: postgres:14-alpine
    container_name: ewm-container-db
    ports:
      - "6542:5432"
    environment:
      - POSTGRES_DB=ewm
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=iamroot