drop table IF EXISTS stats CASCADE;



create table if not exists stats (
  id integer GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  app VARCHAR(255) NOT NULL,
  uri VARCHAR(512) NOT NULL,
  timestamp TIMESTAMP NOT NULL,
  ip VARCHAR(30) NOT NULL
);

